### ISSUE TITLE
Where do you get the api key from?

### ISSUE THREAD

**Issue by Apoo711** [matousvolf/clash-royale-dotnet#1]
So I've attempted to use the api key I got from my in game clash royale user settings and the one in the developer.clashroyale.com portal, but they both give me ` ---> ClashRoyaleAPI.InvalidKeyException: The provided API key is not valid.`

This is how I'm setting the api key,

```
            ClashRoyale.Key = "myKey";
            var data = ClashRoyale.GetClanByTag(name);
```

**Comment by matous-volf** [comment]
Hi, thanks for opening an issue for this.
By the API key I mean the one from developer.clashroyale.com, not the in-game one. Please make sure you're using the latest version (v1.0.2) of this package. It is also required to add your IP address to the key's allowed IPs ([here](https://developer.clashroyale.com/#/account)).

**Comment by Apoo711** [comment]
Hello, thank you for the super quick response.

I have added the ip (fetched from https://myip.com/) and remade the key just to be sure but it seems to throw the same error.

**Comment by matous-volf** [comment]
Okay, thanks for the confirmation.

The exception you're getting is thrown when the official API returns a 403 (forbidden) response code.
That happens when
1. the key is not correct (which you made sure it is), or
2. the IP address is somehow not allowed.

What you could try is to use the [RoyaleAPI proxy servers](https://docs.royaleapi.com/#/proxy).
Just create a new key and add `45.79.218.79` to the allowed IPs and then enable the proxy in this package:
```cs
using ClashRoyaleAPI;

ClashRoyale.Key = "<the_key>"; // the key with 45.79.218.79 allowed
ClashRoyale.UseProxyServers = true; // enable proxy

Clan clan = ClashRoyale.GetClanByTag("<clan_tag>");
```

**Comment by Apoo711** [comment]
Sorry for the late response but, I followed the exact steps above but it still throws the same error.

**Comment by matous-volf** [comment]
Just to be 100 percent sure, try pasting this:
```cs
ClashRoyale.Key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjNlYWViN2QyLTVhZWQtNDk0OC05NDY1LTA5NTRlMjM2YjAyMyIsImlhdCI6MTY1NDY5NjI3NSwic3ViIjoiZGV2ZWxvcGVyLzJiYzEzODVhLWExMzItMDJlYy0zYzFlLTk5ODQ5MmI4ZmJjNCIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI0NS43OS4yMTguNzkiXSwidHlwZSI6ImNsaWVudCJ9XX0.PdjBZ0ddLdMxeRsTNJOTPMg18DOJiI2gzauw0k4fADuSj2hEg7mn2V3xzcrGk2R_WJxbVNK_gqVCnPzuHbXavg"; // the key with 45.79.218.79 allowed

ClashRoyale.UseProxyServers = true; // enable proxy

Clan clan = ClashRoyale.GetClanByTag("L2QCY2VC");

Console.WriteLine("The Clan's name is: " + clan.Name);
```
into an empty project with this package v1.0.2 installed. I've temporarily created the key for you.

If it still won't work, it seems like there's a problem with the internet connection. Not necassarily on your side, perhaps a bug I am not aware of. You could try using a VPN.

You might also consider running the code on a different device/network, either yours or some third party's.

**Comment by Apoo711** [comment]
The key you sent above seems to work, which I think means that I messed up my IP configurations when creating the key.

When you were creating your key, did you just add `45.79.218.79` this IP or that IP with the one that's running code because I did the latter and afaik it should have worked.

**Comment by matous-volf** [comment]
I only put `45.79.218.79` to the allowed IPs. As you're saying, that probably is the problem. Although I would assume it should work either way. This is the key setup:

![image](https://user-images.githubusercontent.com/66163112/172827208-e2843f56-4460-438f-886f-5c7be42fb63d.png)

**Comment by Apoo711** [comment]
So I got the api key sorted out, but api response times are super slow ~ like 24 minutes slow lol.

![image](https://user-images.githubusercontent.com/69662328/172849177-627e6349-78db-4bc6-9450-490691c43404.png)

In the image above, I run the same command twice, which both take 24 minutes each to respond, the functions are fully asynchronous.

**Comment by matous-volf** [comment]
Great you figured it out!

Also thank you for reporting the ultra long response times. I created #2 for that.
I'm gonna fix it ASAP – probably in a few hours – and release a new version.
