### ISSUE TITLE
`GetClansBySearch()` response time is high

### ISSUE THREAD

**Issue by matous-volf** [matousvolf/clash-royale-dotnet#2]
When searching for queries with large number of results, the response takes a lot of time.
The reason is known and will be fixed.

**Comment by matous-volf** [comment]
Fixed in [version 2.0.0](https://github.com/matousvolf/clash-royale-dotnet/releases/tag/v2.0.0).
@Chii-Onan, check please.

**Comment by Apoo711** [comment]
Thank you for fixing it so quickly!

**Comment by Apoo711** [comment]
Also, slightly unrelated to this issue, but it seems that in the latest release, descriptions were removed when getting a clan using GetClanBySearch()

**Comment by matous-volf** [comment]
You are correct. That is because this method returns an array of `SearchResultClan`s. This class matches the official API model, which doesn't include the Clans descriptions in the search results.

If you want the descriptions, you'll have to call `GetClanByTag()` with the `SearchResultClan`'s Tag.
This cannot be done automatically in the `GetClansBySearch()` as that would dramatically increase the response time, which, by the way, actually was the problem causing this issue (#2).

**Comment by matous-volf** [comment]
I am considering adding `GetFullClan()` or something like that to `SearchResultClan` which would do that from the inside of the class. Maybe it's gonna be included in some upcoming version.

**Comment by Apoo711** [comment]
Ah yep thank you, for now I'll just use the method you just suggested while monitoring the response times.

Thank you once again!
